### ISSUE TITLE
ComponentWillReceiveProps is now UNSAFE

### ISSUE THREAD

**Issue by MattiaCostamagna** [react-qr-reader/react-qr-reader#149] opened 2020-02-10 13:37 UTC
Hi!

I just wanted to point out a warning thrown by React in the newer version that complains about the use of componentWillReceiveProps which is now deprecated.

This is the text of the warning:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Reader
```

Thank you!

**Comment by PeterTheOne** [comment] 2020-05-20 14:35
duplicate of https://github.com/JodusNodus/react-qr-reader/issues/138

**Comment by iamgutz** [comment] 2020-12-14 23:24
The warning `componentWillReceiveProps` is still happening, it was reported over 1 year ago in #138 but still seems like it's not merged nor fixed. Any plans on fixing this? :)

**Comment by JodusNodus** [comment] 2022-02-05 20:05
Will be fixed in next release.

**Closed by JodusNodus** 2022-02-05 20:05 UTC
